FROM violinist/php-base:7.1-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN composer require composer/composer:^2 --update-with-dependencies \
    && composer install --no-dev --optimize-autoloader

CMD ["php", "runner.php"]
