FROM violinist/php-base:7.0-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN composer require composer/composer:^2 --update-with-dependencies \
    && composer install --no-dev --optimize-autoloader \
    && patch -p1 < patches/composer2.patch

CMD ["php", "runner.php"]
